spring:  
  jpa:  
    hibernate:  
      ddl-auto: validate  
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect  
  datasource:  
    url: "jdbc:postgresql://172.17.0.2:5432/codingdojospringboot"  
    username: codingdojospringboot  
    password: codingdojospringboot
